#!/usr/bin/env bash
#
# Update the macro-claude formula in the lexfrei/homebrew-tap repository
# to point at a freshly-published GitHub release.
#
# Usage:
#   scripts/brew-bump.sh v0.2.2
#
# The script:
#   1. Verifies the target release exists and contains MacroClaudePlugin.lplug4.
#   2. Downloads the .lplug4 artefact to a temp dir.
#   3. Computes its sha256 with shasum -a 256.
#   4. Rewrites Formula/macro-claude.rb in the local homebrew-tap clone
#      from a heredoc template (idempotent — works for both init and bump).
#   5. Commits and pushes to master in the tap repo.
#
# Requirements:
#   - gh CLI authenticated with read access to lexfrei/macro-claude
#     and write access to lexfrei/homebrew-tap.
#   - Local clone of the tap at TAP_DIR (default ~/git/github.com/lexfrei/homebrew-tap),
#     on master, without dirty changes.

set -o errexit -o nounset -o pipefail

TAG="${1:-}"
if [[ -z "${TAG}" ]]; then
    echo "usage: $0 <TAG>  (e.g. v0.2.2)" >&2
    exit 1
fi
if [[ "${TAG}" != v* ]]; then
    echo "TAG must start with 'v' (got '${TAG}')" >&2
    exit 1
fi
VERSION="${TAG#v}"

REPO="${REPO:-lexfrei/macro-claude}"
TAP_REPO="${TAP_REPO:-lexfrei/homebrew-tap}"
TAP_DIR="${TAP_DIR:-${HOME}/git/github.com/lexfrei/homebrew-tap}"
ARTIFACT="MacroClaudePlugin.lplug4"
FORMULA_REL="Formula/macro-claude.rb"

if ! command -v gh >/dev/null 2>&1; then
    echo "gh CLI not found in PATH" >&2
    exit 1
fi

echo "==> Verifying release ${TAG} in ${REPO} has ${ARTIFACT}"
ASSET_URL=$(gh release view "${TAG}" --repo "${REPO}" \
    --json assets --jq ".assets[] | select(.name == \"${ARTIFACT}\") | .url")
if [[ -z "${ASSET_URL}" ]]; then
    echo "Release ${TAG} in ${REPO} does not contain ${ARTIFACT}" >&2
    echo "Run 'make release-plugin && make release-upload TAG=${TAG}' first." >&2
    exit 1
fi

WORK_DIR=$(mktemp -d)
trap 'rm -rf -- "${WORK_DIR}"' EXIT

echo "==> Downloading ${ARTIFACT} from release ${TAG}"
gh release download "${TAG}" --repo "${REPO}" \
    --pattern "${ARTIFACT}" \
    --dir "${WORK_DIR}"

SHA256=$(shasum -a 256 "${WORK_DIR}/${ARTIFACT}" | awk '{print $1}')
echo "==> sha256: ${SHA256}"

if [[ ! -d "${TAP_DIR}/.git" ]]; then
    echo "Tap clone not found at ${TAP_DIR}" >&2
    echo "Clone it first: gh repo clone ${TAP_REPO} ${TAP_DIR}" >&2
    exit 1
fi

echo "==> Syncing tap at ${TAP_DIR}"
DIRTY=$(git -C "${TAP_DIR}" status --porcelain)
if [[ -n "${DIRTY}" ]]; then
    echo "Tap clone has uncommitted changes, aborting" >&2
    echo "${DIRTY}" >&2
    exit 1
fi
git -C "${TAP_DIR}" checkout master
git -C "${TAP_DIR}" pull --ff-only origin master

FORMULA_PATH="${TAP_DIR}/${FORMULA_REL}"
echo "==> Writing ${FORMULA_REL}"
mkdir -p "$(dirname "${FORMULA_PATH}")"
cat > "${FORMULA_PATH}" <<EOF
# typed: false
# frozen_string_literal: true

# This file is generated by scripts/brew-bump.sh in lexfrei/macro-claude.
# Do not edit by hand — run 'make brew-bump TAG=vX.Y.Z' instead.
class MacroClaude < Formula
  desc "Logi MX Creative Console plugin showing Claude Code session statuses"
  homepage "https://github.com/lexfrei/macro-claude"
  version "${VERSION}"
  url "https://github.com/lexfrei/macro-claude/releases/download/${TAG}/${ARTIFACT}"
  sha256 "${SHA256}"
  license "MIT"
  depends_on :macos

  def install
    # .lplug4 is a zip archive of the LPS plugin package (bin/ + metadata/).
    system "unzip", "-q", cached_download, "-d", libexec
  end

  def caveats
    plugins_dir = "\$HOME/Library/Application Support/Logi/LogiPluginService/Plugins"
    <<~EOS
      Point Logi Plugin Service at the brew-managed copy by writing a
      .link file with the install prefix:

        printf '%s' '#{libexec}' > \\\\
          "#{plugins_dir}/MacroClaudePlugin.link"

      Touch the same file to force LPS to reload it. Before
      'brew uninstall macro-claude', remove the .link file:

        rm -f "#{plugins_dir}/MacroClaudePlugin.link"
    EOS
  end

  test do
    assert_predicate libexec/"bin/MacroClaudePlugin.dll", :exist?
    assert_predicate libexec/"metadata/LoupedeckPackage.yaml", :exist?
  end
end
EOF

if git -C "${TAP_DIR}" diff --quiet -- "${FORMULA_REL}"; then
    echo "==> Formula already up to date, nothing to commit"
    exit 0
fi

echo "==> Committing and pushing"
git -C "${TAP_DIR}" add "${FORMULA_REL}"
git -C "${TAP_DIR}" commit --signoff \
    --message "chore(macro-claude): bump to ${TAG}"
git -C "${TAP_DIR}" push origin master

echo "==> Done. Install with: brew install ${TAP_REPO}/macro-claude"
